In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np

In [ ]:
!pip install numpy

In [ ]:
np.__version__

Vector or 1D Array

In [ ]:
x = np.array([1,2,3,4,5,6,7])
x

Matrix or 2D array

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
x[1:-4]

In [ ]:
#a[0:2,1]=0
#a

In [ ]:
a[1,:]=0
a

In [ ]:
x[x[4]]

In [ ]:
sorted(x, reverse=True)

In [ ]:
#Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
#
#
#

In [7]:
ex2 = np.random.rand(10,5)
ex2[:,-1] = np.round(ex2[:,-1])
ex2

array([[0.24871196, 0.86623869, 0.56232206, 0.39897111, 0.        ],
       [0.2400683 , 0.20051494, 0.84282789, 0.72055203, 0.        ],
       [0.47927544, 0.34253654, 0.3693097 , 0.41033369, 1.        ],
       [0.70431791, 0.77504264, 0.51111622, 0.24013866, 1.        ],
       [0.59836007, 0.21925416, 0.26888593, 0.45031388, 1.        ],
       [0.51349885, 0.57545895, 0.7471249 , 0.68364952, 0.        ],
       [0.520746  , 0.77963337, 0.50845609, 0.44397722, 1.        ],
       [0.95828868, 0.7286155 , 0.44557891, 0.98749451, 0.        ],
       [0.14096814, 0.02628509, 0.45998354, 0.66139087, 1.        ],
       [0.6181668 , 0.73244163, 0.8382409 , 0.63259226, 1.        ]])

In [9]:
#Ex 3. Why we cannot use this index ? Please fix it !!
np_matrix = np.random.randint(3,size = (5,5))
idx = [1,2,3,4,5]
np_matrix[idx,:]
#เพราะindexมีแค่ 0-4 ไม่มี 5

IndexError: index 5 is out of bounds for axis 0 with size 5

In [23]:
#Ex 3. Fix
np_matrix = np.random.randint(3,size = (5,5))
idx = [i-1 for i in idx] 
np_matrix[idx,:]


array([[2, 2, 1, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 1, 2, 2],
       [1, 1, 1, 0, 2],
       [2, 1, 0, 0, 2]])

In [24]:
# Ex 4. Randomly create a data matrix of 10 samples with 5 features.  
# Then, randomly create a label vector for 10 samples.  
# Finally, seperate samples into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)

In [42]:
rng = np.random.RandomState(0)
matrix = rng.randint(10,size=(10,5));
matrix

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7],
       [3, 2, 7, 2, 0]])

In [40]:
label = rng.randint(2,size=(10));
label

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0])

In [44]:
test_data = matrix[np.where(label == 0)]
test_data

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3],
       [3, 2, 7, 2, 0]])

In [45]:
train_data = matrix[np.where(label == 1)]
train_data

array([[7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7]])